# Generated by Django 4.0.10 on 2023-04-03 17:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 3, 17, 32, 18, 608914, tzinfo=utc)),
        ),
    ]
